server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      "local": "console-logging"
      "test": "console-logging"

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false

